### PR TITLE
directory reorganization for tests and examples

### PR DESCRIPTION
**Pull request by dankeefe**
Based on our conversation on Friday, this change gets rid of the "examples" directory -- we will move real "examples" that application programmers should follow to an external repo.  And, adds two sets of tests directories:  tests-batch and tests-interactive.  The idea is that everything in tests-batch should be able to be run in a batch mode, we might even run these by script as part of a nightly build.  Everything in tests-interactive requires someone to actually use the application interactively (e.g., VR, graphics) -- these are small programs that can be used for debugging if something goes wrong.  For example, one tests the opengl fixed function pipeline.  Another tests the opengl shader pipeline...

### CODE REVIEW

**Review by tsgouros — DISMISSED** [review]
This seems like it also includes a bunch of changes on the beta-float branch, that I have a pull request pending onto. I think if you merge here before there it will make a mess.

**Comment by dankeefe** [comment]
There's a backlog of pull requests here.  I think the first two that I entered need to be approved before yours can be, right?

**Comment by tsgouros** [comment]
This one seems to be headed to the "MinVR:beta" branch, from your own "beta" branch. I think you also did something with the MinVR:beta-withfloats branch, and I submitted a pull request to that branch. So if you approve these changes, with your new ones, and delete the beta-withfloats, which seems to duplicate this, you'll lose the changes I made over the weekend to accommodate the double->float change. I might be misunderstanding git branches and pull requests here, but I think that's what is going on.

**Comment by dankeefe** [comment]
The "beta" branch in my personal repo is not the same as the "beta" in the official MinVR repo.  Mine already includes the beta-withfloats changes.  However, it doesn't include your changes.  So, I think what I need to do is to merge with yours.  I'll see if I can figure that out.

**Comment by dankeefe** [comment]
Ok, the pull request has now been updated to include a merge with tsgouros/floattest.  I think it now incorporates all recent changes.

Note: I was using the MinVR/issue88 and MinVR/beta-with-floats branches as if they were my own personal branches with the idea that it would be easier for you all to see the changes in them and check them out if they were branches on the main repo rather than hidden in my personal repo.  However, I think this may have confused the process because now we have some pull requests going into MinVR/beta and others going into MinVR/beta-with-floats.    We can delete MinVR/issue88 and MinVR/beta-with-floats as soon as those changes are merged into MinVR/beta and then just proceed with everyone developing in their own repos and then submitting pull requests directly to MinVR/beta if we want.

**Review by tsgouros — APPROVED** [review]
This seems ok to me, but I am having trouble getting a program to work that did work before, after converting what I thought were all the floats, etc. But go ahead and make this the law of the land.

**Pull request merged**
