### PR TITLE
rats

### PR DESCRIPTION
**Pull request by tsgouros**
Hi Dan:

I can't figure out how to push changes directly into the ivlab repo, since I forked to my own. So take these changes -- mostly just documentation additions -- and enjoy, and I'll keep reading github docs, and maybe switch things so I'm just working out of the ivlab version.

Thanks,

 -Tom

### CODE REVIEW

**Comment by dtorban** [comment]
Hey Tom,

I added you as a contributor to the MinVR2 project.  Let me know if you
have issues writing to the repository.

Thanks,
Dan

**Comment by tsgouros** [comment]
Thanks, that will probably help. But I still don't know how to get these changes in. Is there some "accept pull request" button that needs to be clicked? I set the ivlab repo up as an upstream master, and seem to be able to pull from it, but 'git push upstream master' fails.

**Comment by dtorban** [comment]
What is the error getting with git push upstream master?

Can you also type the following command from your local and send me your
remote information:
git remote -v

Thanks,
Dan

**Comment by tsgouros** [comment]
config$ git push upstream master
Password for 'github.com':
error: The requested URL returned error: 403 while accessing
https://tsgouros@github.com/ivlab/MinVR2/info/refs
fatal: HTTP request failed
config$ git remote -v
origin    https://github.com/tsgouros/MinVR2.git (fetch)
origin    https://github.com/tsgouros/MinVR2.git (push)
upstream    https://tsgouros@github.com/ivlab/MinVR2 (fetch)
upstream    https://tsgouros@github.com/ivlab/MinVR2 (push)

**Comment by dtorban** [comment]
Hey Tom,

Try again, apparently I forgot to add the repository to the MinVR2Dev
group.  Let me know if it works this time.

Thanks,
Dan

**Comment by tsgouros** [comment]
Hey presto look at that!

Thanks,

 -Tom

**Comment by tsgouros** [comment]
And I also see that doing a git push from my local repo seems to have
approved the pull request from my github repo to yours. That's a little
mysterious, but I suppose it's a good thing.

Thanks,

 -Tom

**Pull request merged**
