### PR TITLE
Open vr and windows fixes

### PR DESCRIPTION
**Pull request by BenKnorlein**
I updated OpenVR to the newest version 1.0.6 and also applied several fixes for the plugin.

Also in the pull request for building MinVR on Windows.

The VRSystem time was not working. Someone please check if it is correct like this.
Also the shader example did not build as it requires glew on Windows. Hope it works now.

### CODE REVIEW

**Review by tsgouros — COMMENTED** [review]
Are we not using glew on Mac and Linux? I have been using it in my examples there.

Someone who is using Windows should approve this before merging it.

**Comment by BenKnorlein** [comment]
Not sure. On Windows it will otherwise not compile. It needs glew for 
the glGenBuffers etc.

**Comment by tsgouros** [comment]
That's not what I meant. I meant that I also need it on Mac and Linux, so you shouldn't ifdef it out.

**Comment by BenKnorlein** [comment]
You need it for the shader example? If so we should always include it. I 
am not sure if i did need it for linux.

Ben

**Review by dtorban — APPROVED** [review]

**Comment by dtorban** [comment]
Okay, I merged beta into Ben's changes, it should be good to merge into beta now.

**Pull request merged**
