### PR TITLE
Added simple VR Application abstraction.

### PR DESCRIPTION
**Pull request by dtorban**
The following were added to the core of MinVR:
- Added MinVR graphics API (Based on Dan Keefe's implementation)
- Created minimal graphics example (To show a simple example)
- Created modern shader example application (To show a more complex example)

I added a base class for simple graphics applications called [VRGraphicsApp](https://github.com/dtorban/MinVR2/blob/api/src/api/graphics/VRGraphicsApp.h) based on Prof. Laidlaw's suggestion.  This would be the best place to start.  Here is example code on implementing it:

```c++
  #include <api/MinVR.h>
  class MyVRApp : public VRGraphicsApp {
  public:
	MyVRApp(int argc, char** argv, const std::string& configFile) : VRGraphicsApp(argc, argv, configFile) {}
	virtual void onVRRenderGraphics(VRGraphicsState& renderState) {
		// draw graphics
	}
  };
  int main(int argc, char **argv) {
    // The second argument is the config file path for this example
	MyVRApp app(argc, argv, argv[1]);
	app.run();
	return 0;
  }
```

Finally, I added two example applications:
-  [MinGraphicsExample/main.cpp](https://github.com/dtorban/MinVR2/blob/api/examples/MinGraphicsExample/main.cpp)
- [ShaderExample/main.cpp](https://github.com/dtorban/MinVR2/blob/api/examples/ShaderExample/main.cpp)

### CODE REVIEW

**Comment by dtorban** [comment]
By the way, in creating the API abstraction based on Dan K's suggestion, I pretty much only added the following folder:

[https://github.com/dtorban/MinVR2/tree/api/src/api](https://github.com/dtorban/MinVR2/tree/api/src/api)

The more flexible MinVR code was hardly touched at all.

**Comment by dtorban** [comment]
I forgot to mention, I only made changes for RenderHandler and not EventHandler.  I imagine EventHandler would require more discussion.

**Comment by dtorban** [comment]
**Here is the latest API branch:**

- [API Headers](https://github.com/dtorban/MinVR2/tree/api/src/api)

CPP files (Notice that I moved all the headers up to the src/api level.  I put the cpp files in the src/api/impl for now):
- [API Source](https://github.com/dtorban/MinVR2/tree/api/src/api/impl)

**Changes that were made:**

- Created [VRApp](https://github.com/dtorban/MinVR2/blob/api/src/api/VRApp.h) generic applications and [VRGraphicsApp](https://github.com/dtorban/MinVR2/blob/api/src/api/VRGraphicsApp.h) for rendering graphics. (Dan K's and Ben's suggestion)
- Modified [VRRenderHandler](https://github.com/dtorban/MinVR2/blob/api/src/api/VRRenderHandler.h)
  - Removed the onVRRenderContext(...) and onVRRenderScene(...) callbacks.  Replaced with a simple generic  onVRRender(...) callback since other devices may not have a graphics context.
  - These graphics specific callbacks (context and scene) now exist in the [VRGraphicsHandler](https://github.com/dtorban/MinVR2/blob/api/src/api/VRGraphicsHandler.h).
- [VRGraphicsHandler](https://github.com/dtorban/MinVR2/blob/api/src/api/impl/VRGraphicsHandler.cpp) implementation checks to see if there is a graphics context before calling the onVRRenderGraphicsContext(...) or onVRRenderGraphicsScene(...).  If there is no graphics context, the render methods are not called.  I also added a VRDataIndex value of "Render" which tells whether to render in "Context" or in "Scene".  Here is the update in the [VRGraphicsWindowNode](https://github.com/dtorban/MinVR2/blob/api/src/display/VRGraphicsWindowNode.cpp) (Ben's suggestion):
   ```c++
	renderState->addData("HasGraphicsContext", 1);

	// windows should call the application programmer's context-level callback
	renderState->addData("Render", "Context");
	renderHandler->onVRRender(renderState, this);

	renderState->addData("Render", "Scene");
   ```

- Changed [VRGraphicsState](https://github.com/dtorban/MinVR2/blob/api/src/api/impl/VRGraphicsState.cpp) implementation to always get matrices assuming that VRDataIndex could change (Ben's suggestion).
- Used opaque pointers to remove the private member variables from the header files. (Dan K's suggestion)

**Comment by dankeefe** [comment]
Note the dank-api branch just added today is a follow-on to this issue.

**Comment by tsgouros** [comment]
The conflicts here are due to my fixes of the data index usage, mostly substituting "/Eye" for "Eye" and that kind of thing. They are not a big deal to accept.

**Comment by dtorban** [comment]
Closing pull request for now since DanK has another version in [dank-api](https://github.com/MinVR/MinVR/tree/dank-api) branch.

**Pull request closed without merging**
