### PR TITLE
Added C++11 Cross Platform Frame Timer.

### LINKED ISSUE #90: Move creating the standard MinVR "ElapsedTime" / "StartFrame" event to VRMain.cpp
Right now, an event is created once each new frame that holds a double data field for the elapsed time in seconds since the program started up.  A couple of our example programs depend on this.  I think it's a fine idea to have an elapsed time event that gets generated once per frame as part of MinVR, but if application programmers are going to depend on this, then the event should be created within the core of MinVR rather than in a plugin to avoid the possibility of some future plugin authors forgetting to create this important event or calling it by a different name, etc.

I think the reason it is not part of VRMain now is that it is implemented using getGLFWTime() -- moving it to VRMain is not completely trivial because we would need our own system call for getting the current time that works across Windows, OSX, Linux etc.

### PR DESCRIPTION
**Pull request by dtorban**
I added a plugin which creates a cross platform frame timer as an input device.  This fixes #90.  The idea is that per frame it will output the number of seconds since the program started.  It relies on the c++11 plugin for simplicity and ability to work across platform, but it is possible to create other types of timers.

Output will be the following event: /FrameStart/ElapsedSeconds

To get it to work add the following to your config file:

```xml
<MinVR>
        ...
	<CPP11Plugin pluginType="MinVR_CPP11"/>
        <Timer inputdeviceType="VRCpp11Timer"/>
         ...
</MinVR>
```

### CODE REVIEW

**Comment by dtorban** [comment]
By the way, I made it a plugin since it relies on c++11.  I also made it an input device because it was really easy to do with our system.

**Comment by dankeefe** [comment]
@dtorban did you get a sense while implementing this of how challenging it would be to do it in a way that doesn't require C++-11?  I'm just thinking that if we want this to be sort of a standard event that everyone can depend on being there, it's probably something that should be in the core rather than a plugin.

**Comment by dtorban** [comment]
Looks like most people are suggesting the use of boost or c++11 for high precision timing.  I started dissecting GLFW timing, but it took longer than I thought.  It looks possible, but looks pretty involved as it needs to be implemented and tested differently in many different environments.

I wanted to do it as easy as possible for now, which wasn't dependent on the windowing library.  The current way we are doing in GLFW won't work because every process that uses GLFW will report a different time.  I figured the c++11 plugin approach was simple, flexible, and a fairly standard way to do it (or at least the recommended way).  It was also really easy to code.  If someone doesn't have C++11 available, they could always write another timer input device specific to that system or use Boost.

In my opinion the C++11 plugin approach is much easier and cleaner than writing all the system specific logic, which may not work for all systems anyhow.  I'll continue to look into it; this was just an easy way forward.  The CPP11 plugin could also be one of the base plugins, so it would be standard in MinVR.

**Comment by dtorban** [comment]
By the way, this does not tie us to C++11, it just allows us to easily use it.

**Comment by dtorban** [comment]
Oh wait, just had a great idea to allow for non-c++11. I'll try it out and resubmit.

**Comment by dankeefe** [comment]
Cool.  G3D has a non C++11 implementation as well.  So, that could be another point of reference.

**Comment by dtorban** [comment]
Cool, okay will check it out

**Comment by dtorban** [comment]
Closing for now

**Pull request closed without merging**
