### PR TITLE
Added Multithreaded Test Application with GPU Affinity

### PR DESCRIPTION
**Pull request by dtorban**
Hey Team,

I added a test application here which uses a Model View Controller approach to VR.  (This appears to be necessary for using multiple render contexts):

[opengl-multithreaded Test Application](https://github.com/dtorban/MinVR2/tree/multithreaded/tests-interactive/opengl-multithreaded)

I Updated the Threading plugin so you can just include "-DMINVR_THREADING_PLUGIN" when calling cmake to enable threading.

I also added the GPU Affinity functionality in Windows using Bret's version of GLFW.  It will now figure out what graphics card you are running if you enable UseGPUAffinity in the config.

Here is an example config for using multithreading in Windows:

[multithreaded.minvr](https://github.com/dtorban/MinVR2/blob/multithreaded/config/desktop-multithreaded.minvr)

To test the application use

```bash
build/bin/itest-opengl-multithreaded -c desktop-multithreaded.xml
```

Let me know if you guys have any questions.

Thanks,
Dan

### CODE REVIEW

**Comment by tsgouros** [comment]
Is this a test, or just an example application?

**Comment by dtorban** [comment]
Yes, it is a test as it tests multithreading and GPU Affinity.

**Comment by dtorban** [comment]
You will see a rotating cube in two windows if it is working.

**Comment by dtorban** [comment]
Right now the test is a quick sanity check, but I plan on improving it later. It actually represents a suite of tests for the following: MVC approach, multithreaded approach, and gpu affinity, which are all closely related.  Something like MVC is necessary for multiple multithreaded views.  I plan on having multiple test configurations to test each with the app. Let me know if I should choose a different name for the collection of tests.

**Comment by bretjackson** [comment]
I noticed this uses VRMatrix4. I thought we were going to try to use
something like glm in tests/examples so that users don't get confused. I
think it would be better to only use the VR math library inside the core.

**Comment by tsgouros** [comment]
Agreed: the VRMatrix4 is sort of why I was asking. Also, I really wish stuff like this had tests that could be executed with make test. I know the whole thing can't be tested that way, but some of it can.

**Comment by dtorban** [comment]
I copied opengl-shaderpipeline for simplicity, but I can definitely remove VRMatrix4.  It was not the point of the test.

**Comment by dtorban** [comment]
Okay, I removed the reference to VRMatrix in the test.

**Comment by dtorban** [comment]
Okay, this should be up to date with the latest beta now.

**Comment by dtorban** [comment]
Hey Team,

I was able to get shared contexts to work.  We can now share objects across windows!  This means we can take advantage of only uploading or updating large objects like VBO's and Textures once per graphics card.  The windows would have access to these objects and could each render them their own way.

Here are the three cases that this test currently supports:

```bash
# Normal output without multithreading
build/bin/itest-opengl-multithreaded -c desktop
# Opens two multithreaded windows
build/bin/itest-opengl-multithreaded -c desktop-multithreaded
# Opens four multithreaded windows with one shared context for the vbo
build/bin/itest-opengl-multithreaded -c ivlabcave-desktop
```

Here is a UML diagram of the MVC approach:

MVC Overview

Please see the [README](https://github.com/dtorban/MinVR2/blob/multithreaded/tests-interactive/opengl-multithreaded/README.md) for more details.

Thanks,
Dan

**Comment by dtorban** [comment]
This pull request is ready for review again.  I updated the documentation to show test validation in the [README](https://github.com/dtorban/MinVR2/blob/multithreaded/tests-interactive/opengl-multithreaded/README.md).

**Review by dankeefe — APPROVED** [review]

**Pull request merged**
