### PR TITLE
fixed VRSearchPath to have INSTALLPATH inserted at cmake-time

### PR DESCRIPTION
**Pull request by tsgouros**
This addresses a problem with the way VRSearchPath.h was handled before. I'd used "add_definitions" in cmake to include the install directories in the search path, and that worked for the library, but not for the installed header file to be used with the library. This fix removes VRSearchPath.h as a part of the source, and replaces it with VRSearchPath.hpp that is auto-edited to create the .h file. The auto-edit happens at cmake-time, so it's available at compile time.

### CODE REVIEW

**Comment by dtorban** [comment]
Is there a reason we would use auto generated files instead of pre-processor defines?  I'm just more familiar with defining a value at compile time, but perhaps this is a better way.

Here is the way I'm familiar:

```cmake
add_definitions(-DINSTALLPATH="${CMAKE_INSTALL_PREFIX}")
```

**Comment by tsgouros** [comment]
That is the way I implemented it at first, using add_definitions(). The problem is that the header files are also supposed to be available to a user where MinVR has been installed on their machine. They would install the compiled library, but the uncompiled header files, and I couldn't figure out a way to use add_definitions() to add definitions to a file that was only copied from the source to the install directories. If you know how to make add_definitions() do that, do tell.

**Comment by dtorban** [comment]
Okay cool.  One approach to make add_definitions work would be to create a VRSearchPaths.cpp and put the implementation there instead of the header file.  I imagine it is fine either way :).

**Comment by tsgouros** [comment]
You're right, that's a better way. I'll adjust the pull request. Thanks.

**Comment by tsgouros** [comment]
Pull request adjusted, the INSTALLPATH is only used inside VRSearchPath.cpp, where the add_definitions() functionality can get at it.

**Review by dtorban — APPROVED** [review]
Looks good to me

**Pull request merged**
