### PR TITLE
Centralized / installed config files

### PR DESCRIPTION
**Pull request by dankeefe**
This is a fairly significant pull request in that it shifts us into the mode of having centralized common config files (desktop, YURT, ivlabcave, etc..) that exist in one common place in the build directory rather than having multiple copies included with each example app.  In the build directory, the configs are in MinVR/config  and the files there get installed to INSTALL_PREFIX/config.  I also changed the config file extensions to .minvr rather than .xml.  The .minvr extension is used to distinguish installed vs. uninstalled config files when they are listed on the command line (see below).

This pull includes a default MinVR command line convention that is updated a bit from before.  It now supports 3 things:  (1) loading pre-installed configurations, (2) loading regular config files that have not been pre-installed, and (3) setting specific overrides with a key=value argument.  The help message for the command line is copied below.  Also, since some users may not want to use this command line convention, there are two distinct ways to initialize MinVR in this branch:  (1) VRMain::initializeWithMinVRCommandLineParsing() and (2) VRMain::initializeWithUserCommandLineParsing().  There is a caveat with the user command line parsing in that users must write their command line parser so that it ignores a special argument of the form MINVR_DATA=xxxxxxx so that MinVR can pass data to subprocesses.  This uses @dtorban's approach for encoding data on the command line in a single argument so it is not too hard for users to ignore if they really want to do their own command line parsing.

@dtorban I adjusted the VRAppLauncher code a bit to make this work.  Can you please review that specifically and make sure that I did not cause a problem for how you intend for that feature to be used.  I'm not sure if I completely preserved your vision for how developers should use it.  I left a bunch of comments for what I was intending.  As I understand it from the code, it looks like exactly what we would want to use to launch programs over SSH as is done in the YURT, and I wonder if we should write a VRSSHAppLauncher(..) to do that.  I renamed the VRDefaultAppLauncher to VRLocalAppLauncher with the idea that there might be a VRSSHAppLauncher or VRRemoteAppLauncher or VRMPIAppLauncher etc. on the way.  I would guess that the specific app launcher to use is something that could be set via a config file, so as I reorganized the initialize*() functions I did not preserve the ability to send a VRAppLauncher into the initialize() function.  Do you foresee any problem with that?  Let me know if I have the right idea on this... I want to make sure that this doesn't squash any idea you had for how to use it.  Thanks!

New default MinVR command line args:
```
-h, --help         Display this help message.

<configname>       Search for and load the pre-installed MinVR config file
                   named <configname>.minvr -- the search looks in:
                   1. the current working directory [cwd]
                   2. [cwd]/config
                   3. ../../config (for developers running build tree
                      executables from build/bin or tests/testname
                   4. MINVR_ROOT/config if the MINVR_ROOT envvar is defined
                   5. the install_prefix specified when libMinVR was built.

<path/file.minvr>  Load the exact MinVR config file specified as a complete
                   relative or absolute path and filename.  The filename
                   must include a .minvr extension to distinguish this
                   option from loading a pre-installed configuration.

<key>=<value>      Add an entry to the MinVR configuration directly from
                   the command line rather than by specifying it in a
                   config file. This can be used to override one specific
                   option in a pre-installed configuration or config file
                   specified earlier on the command line.  For example,
                   'myprogram desktop WindowHeight=500 WindowWidth=500'
                   would start myprogram, load the installed desktop MinVR
                   config and then override the WindowHeight and
                   WindowWidth values specified in the pre-installed
                   desktop configuration with the new values specified.

[nothing]          If no command line arguments are provided, then MinVR
                   will try to load the pre-installed default
                   configuration, whis is the same as running the command
                   'myprogram default'.

MINVR_DATA=xxxxx   A special command line argument reserved for internal
                   use by MinVR.
  ```

### CODE REVIEW

**Comment by tsgouros** [comment]
This is not quite the directory arrangement we discussed in #108. The config files should be installed into INSTALL_PREFIX/share/config. Would be great if the plugins could go into INSTALL_PREFIX/share/plugins while you're at it.

**Comment by dankeefe** [comment]
I'd like to revisit #108.  It doesn't address the issue of installing multiple versions or windows.  I will post a comment there with a more detailed suggested install layout.

The change in where to install plugins should be submitted to github in a separate pull request / branch based on the mode of working we discussed on Fri.

**Comment by dtorban** [comment]
Does SSH still work?  I think if that is the case, we are good as VRLocalAppLauncher should do the trick there.  VRDefaultAppLoader handled all the cases before (i.e. windows forking, minvr command line, SSH, local, etc...).  Perhaps we could even get rid of VRAppLauncher and VRLocalAppLauncher.  It was originally intended to allow users control of the command line.  This functionality could now be handled with initializeWithUserCommandLineParsing().  I am fine if we get rid of VRAppLauncher all together.

**Comment by dtorban** [comment]
I think one of the original purposes of VRDefaultAppLauncher was so that users who wanted to take control of the command line didn't have to know about the MINVR_DATA= parameter, or they could define it to be something else if they needed.  This is no longer the case, but that's probably fine since taking control of the command line is a more advanced feature.

**Review by tsgouros — APPROVED** [review]
Hear, hear for consolidated config files. I'll get used to the new suffix.

**Comment by dankeefe** [comment]
Thanks, @tsgouros can you / did you already check to see if launching in the YURT via ssh still works?  I want to make sure I didn't introduce a bug in that part with revisions to the VRAppLauncher, but unable to test here.

**Comment by BenKnorlein** [comment]
Hi Dan,
I had to change something in VRMain for it to compile on Linux. You want to add it before merging? 

line 142: std::ifstream infile(fileName.c_str()); instead std::ifstream infile(fileName);
 
Otherwise it started over ssh. But is there still an option to handle commandline yourself? Sometimes it is kind of nice and I was using it with some of my applications recently for providing the path to the data which needs be loaded and displayed.

**Comment by dankeefe** [comment]
Ok, I will add that to the branch.  There is an option to handle the command line yourself by using VRMain directly.  Look at line 109 in VRMain.h for instructions.  It is not part of VRApp because I thought of it as a more advanced option.

**Comment by BenKnorlein** [comment]
Hi Dan,
My problem is more that i cannot add an argument to my program calls which do not have the form of key=value, e.g. in case i just want to provide a data file to display i often used something lie this:
./program config-file data-file
and read the data from argv[2]

Now MinVR thinks that the data-file is a config-file as well and minVR does not start. The only thing i can do now is either parse it myself and create new argc and argv for minVR or use a key=value and read it from the DataIndex or parse the strings myself. 

What do you think of actually using a key= for the config-file as well, e.g.
./program config=config-file1 config=config-file2  data-file
In that way we can say that MinVR always uses key=value pairs.

**Comment by tsgouros** [comment]
My apologies for not focusing on this sooner. Ben and I were talking about this, and I think the flexibility of the command line that you've designed comes to some degree at the expense of the user program's convenience. How does the user conveniently specify an argument to their program? Most such programs are going to want some argument parsing and checking to be done *before* the VRApp object is constructed.

I propose that MinVR can be content with key=value pairs, and any argument that isn't key=value is available to the user's program, perhaps with a static VRApp method that can be called before the VRApp object is constructed. The search path stuff is still fine, though.

**Comment by dankeefe** [comment]
Oh, ok.  I didn't understand your question earlier.  I was designing for 2 cases:
1. Adopt a default command line recommended / supported by MinVR.
2. Create your own totally custom command line and parse it yourself.

If I'm understanding correctly, I think what you're saying is a great idea.  It's sort of like a 1b option -- use MinVR's default command line parsing for the most part so that you don't have to write all that parsing from scratch, but also allow for additional things on the command line (i.e., MinVR could just ignore any arguments it doesn't recognize rather than spitting out an error).  That sounds fantastic to me.

The only challenge in implementing it would be how to distinguish the args MinVR should parse from those it should not.  The = sign idea would work, but now that I think about it more, I wonder if we should try to make the command line more standard, like something that could be parsed with gnu getopt, like:

-c filebasename  or --config filebasename  -->  load an installed config file
-f filename  or --file filename  --> load this specific file (not installed)
-v key=value --> set this key=value option

It could also be --config=filebasename.  It looks like --condition=foo is often used to set a condition and --output-file file.abc is often used when referring to files.  What do you guys think would be the most standard approach to supporting these 3 options?

Great idea... should not be hard to adjust this.

**Comment by tsgouros** [comment]
Ben and I think that sounds fine. Explicitly labeling the args that MinVR needs is good. Just set it up so it can take a more complicated command line and just ignore anything it can't understand. That way the command line can be parsed twice, once by the user program and once by MinVR. If someone grows out of that they can jolly well do the parsing themselves.

One thing to make sure is that you can have multiple --config= clauses and multiple -v k=v clauses, too. Another need the command line is going to require, incidentally, is the ability to export  environment variables, so there should be a -e k=v, also.

**Comment by dankeefe** [comment]
Sounds good.  I'll try to make the edits in the next couple of days.

**Comment by dankeefe** [comment]
Updated based on the online discussion.  New command line format is as follows:

```
        -h, --help         Display a help message.
     
        Add any of the following arguments to the command line as many times as
        needed in a space separated list.
     
        -c <configname>, --load-config <configname>
                           Search for and load the pre-installed MinVR config file
                           named <configname>.minvr -- the search looks in:
                           1. the current working directory [cwd]
                           2. [cwd]/config
                           3. ../../config (for developers running build tree
                              executables from build/bin or tests/testname
                           4. MINVR_ROOT/config if the MINVR_ROOT envvar is defined
                           5. the install_prefix specified when libMinVR was built.
        
        -f <path/file.minvr>, --load-file <path/file.minvr>
                           Load the exact MinVR config file specified as a complete
                           relative or absolute path and filename.
     
        -s <key>=<value>, --set-value <key>=<value>
                           Add an entry to the MinVR configuration directly from
                           the command line rather than by specifying it in a
                           config file. This can be used to override one specific
                           option in a pre-installed configuration or config file
                           specified earlier on the command line.  For example,\n"
                           'myprogram -c desktop -s WindowHeight=500 -s WindowWidth=500'
                           would start myprogram, load the installed desktop MinVR
                           config and then override the WindowHeight and
                           WindowWidth values in the pre-installed desktop
                           configuration with the new values specified.
     
        [nothing]          If no command line arguments are provided, then MinVR
                           will try to load the pre-installed default
                           configuration, whis is the same as running the command
                           'myprogram --load-config default'.
     
        [anything else]    MinVR will silently ignore anything else provided as
                           a command line option.
     
        --MINVR_DATA=xxxx  A special command line argument reserved for internal
                           use by MinVR.
```

**Pull request merged**
