### PR TITLE
Added cross platform time implementation and per frame time event.

### PR DESCRIPTION
**Pull request by dtorban**
To get the time anywhere in the MinVR system use the following method:

```c++
double time = VRSystem::getTime();
```

I also moved the ElapsedTime event to VRMain.

### CODE REVIEW

**Comment by dtorban** [comment]
Fixes #90

**Review by tsgouros — APPROVED** [review]
This is ok with me, especially since it's pretty much the same technique I used in VRDataQueue. You didn't have to go to G3D to get that.

**Comment by tsgouros** [comment]
It would be tidier to change the VRDataQueue code to use VRSystem, so I will do that.

**Comment by dtorban** [comment]
Yep, I also used your code in conjunction with G3D code. Looks like it is
the same approach :).

**Comment by tsgouros** [comment]
Feel free to adapt the VRDataQueue code if you manage to get to it before me.

**Pull request merged**
