### PR TITLE
A lot of changes.

### PR DESCRIPTION
**Pull request by BenKnorlein**
Looking forward to discussions

### CODE REVIEW

**Comment by dtorban** [comment]
The changes look reasonable to me.  I would rename the TypeFactory to something else (perhaps VRFactory or VRBaseFactory?) and use an enum for the switch statement instead of numbers 1-4.  At least then if we change a supported type, it will be a compile error rather than pretending to be a different type.

**Comment by tsgouros** [comment]
My comments are these:
1. +1 on Dan's comment about need either an enum or some defines for the switch.
2. I'm not sure I like the 'displaynode="VRStereoNode" ' construction. This is only a comment on the name itself. I want the value of an attribute to make sense as the answer to a question about the attribute. 'displaygraphnodename' is too long, but what we use should have 'name' or 'kind' or 'type' or 'variety' or something in it somewhere, I think.
3. The VRDataIndex::getNames(namespace) method wasn't implemented partly because I'd forgotten about it, but also partly because getValue() does exactly the same thing, for a container, and is quicker. The global getNames() is useful for debug purposes, and other incidental reasons, but I don't know if you really need getNames(namespace). On basic efficiency concerns, I'd suggest leaving it out, but whatever you like is fine for now.

**Comment by BenKnorlein** [comment]
1. I had the same thoughts as Dans comment. I just wanted to quickly 
   finish it yesterday to get some feedback before i do some polishing. I 
   will do the changes today
2. I thought about "nodetype", but it did not fit the other types and 
   also does not say that it is a displaynode. And i have the feeling 
   displaynodetype or displaynodekind, as well as e.g. graphicstoolkittype, 
   seems a little long and does also not sound nice. "Name" is wrong for me 
   as it is not a name which can be just given. I had the feeling just 
   displaynode described it best, but i am open for any suggestions from 
   the group
3. I was not aware of the getValues. I will change my code and also 
   remove the getNames function completely. I also remove it from 
   VRDataIndex.h as it was not implemented. If we really want a 
   functionality like this later we can add it again.

**Comment by dankeefe** [comment]
I think all the changes in the code look good and are taking us in the right direction.  I think we should talk a bit more about the config file format -- maybe that can be our main topic for Skype tomorrow.  Here are a couple of initial thoughts:

Use of attributes:
- I like going toward more use of XML attributes in general... we haven't really made use of these so far, but they seem like the right thing for specifying things like the "type" of the node.
- However, one possible point of confusion here could be the distinction between what should be an attribute and what should be listed as sub-field of the XML tag.  
- In the examples so far, is the convention that the attributes are only used when we need to know the type of the object, as in what type of display node or what type of toolkit?
- If so, then maybe we should use a "type" attribute for this and just make it a MinVR convention: e.g., <MyStereoNode type="VRStereoNode">...</MyStereoNode>.
- I know that "type" is already used internally by the VRDataIndex, but I'm hoping that that use of the type attribute is quite rare -- it should only be needed in situations where the index can't automatically infer the type for some reason.  So, if "type" is really the right thing for this new feature, then maybe we should switch dataindex to use something else, perhaps "datahint".

Use of hierarchy:
- If we take the path of defining everything via a hierarchical style of XML, then I think we would end up with everything nested.  For example, everything that relates to the Cave (input devices, display graph, toolkits, etc.) would be inside a single XML field <Cave type=VRSetup>...</Cave>.  Something like this seems to be the logical endpoint if we move down a hierarchical path.
- I think something like this might have some key advantages.  It might also have disadvantages, e.g., the issue of needing to replicate the same display graph 69 times.  So, maybe we should discuss those in some more detail.
- However, if we go down this path, then we should keep in mind that it would be quite different from a key=value style of configuration.
- I think that either could work in the end, but right now, it seems like we are half way between hierarchical and key=value, and I wonder if users would have an easier time understanding how to configure MinVR if we were to pick one approach.

**Comment by BenKnorlein** [comment]
I made more changes. They are just a suggestion, so all are only up for discussion:
- I Finished the config i think it should work. Entry is the "hostType" attribute. Than it creates the plugins etc based on the namespace of the namespace of the "hostType"
- DisplayGraph is now a vector of "windows". 
- Toolkits are now created and set when the window is initialised as each window can only have one of each.
- Attributes all have "Type" in the name
- I also added the duplication of children to the Stereorender. Both solutions are not perfect. A) inserts a groupnode. B) restricts the graph to only 1 children per node. I personally would prefer B as i breaks the namespace of the config. However I would insert a max_Children in the VRBaseNode which can be used to define the maximum number of children for each node. For most displaynodes it does not make much sense to have more than 1 child from my point of view.

**Comment by BenKnorlein** [comment]
Also another thing to add. VRMain will now initialise ALL windows, plugins etc which are higher in the namespace. So something like this will result in 2 Windows

<MinVR>
    <RootNode1 windowType="VRGraphicsWindowNode">
    </RootNode1>
    <Desktop host="VRStandAlone">
         <RootNode2 windowType="VRGraphicsWindowNode">
         </RootNode2>
    </Desktop>
</MinVR>

**Comment by dtorban** [comment]
How would you write a config with a hierarchical display graph where a node has more than one child?  For example, a ThreadGroupNode, where all the children are threaded windows?  I think you mentioned this, but I'm having a hard time visualizing in the config.

**Comment by BenKnorlein** [comment]
You just define them at the same level. You can for example just do 3 
windows

<Desktop hostType="VRStandAlone">
     <Window1 windowType="VRGraphicsWindowNode">
...
     </Window1>
     <Window2 windowType="VRGraphicsWindowNode">
...
     </Window2>
     <Window3 windowType="VRGraphicsWindowNode">
...
     </Window3>
</Desktop>

or 3 nodes in a window.

<Window1 windowType="VRGraphicsWindowNode">
     <DisplayNode1 displayNodeType="VROffAxisProjectionNode">
     </DisplayNode1>
     <DisplayNode2 displayNodeType="VROffAxisProjectionNode">
     </DisplayNode2>
     <DisplayNode3 displayNodeType="VROffAxisProjectionNode">
     </DisplayNode3>
</Window1>

Ben

**Comment by BenKnorlein** [comment]
And you only have to define the content once with a copyContent or 
copyNode node, e.g

<MinVR>

```
 <Desktop hostType="VRStandAlone">
     <Window1 windowType="VRGraphicsWindowNode">
         <displayGraph 
```

copyNode="/MinVR/MyDisplayGraph/MyStereoNode"> or <displayGraph 
copyContent="/MinVR/MyDisplayGraph">
         </Window1>
         <Window2 windowType="VRGraphicsWindowNode">
             <displayGraph 
copyNode="/MinVR/MyDisplayGraph/MyStereoNode"> or <displayGraph 
copyContent="/MinVR/MyDisplayGraph">
         </Window2>
         <Window3 windowType="VRGraphicsWindowNode">
             <displayGraph 
copyNode="/MinVR/MyDisplayGraph/MyStereoNode"> or <displayGraph 
copyContent="/MinVR/MyDisplayGraph">
         </Window3>
     </Desktop>

```
 <MyDisplayGraph>

     <MyStereoNode displaynodeType="VRStereoNode">

         .......

     </MyStereoNode>

 </MyDisplayGraph>
```

</MinVR>

**Comment by BenKnorlein** [comment]
I adjusted the ivlab config and added 2 more. I also fixed some bugs in the Stereonode and the VRPN initialisation. Configfiles for ivlab are now:
1 Server + 4 clients each 1 screen
1 Server + 1 client with 4 screens
1 standalone with 4 screens

**Comment by BenKnorlein** [comment]
Hi all,

I just distributed the VROffAxisRendering to different displayNodes. This makes the processing more flexible, e.g. HeadTracking could be used with other projections, e.g. a VRFrustumNode. In addition the VROffaxisRendering had a bug in it when only using Mono. In this case the offset of the eye was still applied as it would have been the left eye.

Ben

**Comment by dtorban** [comment]
Hey Ben, can you fix the conflicts on this pull request to be merged?  I tested on my box and it looks like it works pretty well.

**Comment by BenKnorlein** [comment]
Do you want to push your changes on the master? Then i can merge my onto the master on Monday.

**Comment by dtorban** [comment]
Sure, that sounds great.  I'll push my changes and we'll push your changes
on Monday.

Thanks,
Dan

**Comment by dtorban** [comment]
I just pushed the changes.  Let me know if you have any issues.

**Comment by dtorban** [comment]
You may want to investigate the create method in the [VRItemFactory](https://github.com/ivlab/MinVR2/blob/master/src/main/VRItemFactory.h) as it does things common to all items (perhaps related to your changes):

```
virtual T* create(VRMainInterface *vrMain, VRDataIndex *config, const std::string &valName, const std::string &nameSpace) {
    std::string itemNameSpace = config->validateNameSpace(nameSpace + valName);
    std::string type = config->getValue("Type", itemNameSpace);
    if (type != _typeName) {
        // This factory cannot create the type specified
        return NULL;
    }

    return createConcrete(vrMain, config, valName, itemNameSpace);
}
```

`

**Comment by BenKnorlein** [comment]
I merged my changes with the new Factory. 2 things i had to do apart from combining things:

a) I had to add for the attribute, e.g. whether it is a displayNodeType or windowToolkitType. For this i added a 
`static std::string getAttributeName(){ return "displaynodeType"; };`

to the baseclasses of the different types (inputdevice, windowtoolkit, displaynode, graphicstoolkit). This allows to define the entry which is used in the config-file when a new basetype is added.

b) I had to add some code in the VRConcreteItemFactory to make sure that childnodes are created in case it it is a VRDisplayNode.

```
ParentType* createConcrete(VRMainInterface *vrMain, VRDataIndex *config, const std::string &itemNameSpace) {
    ParentType* item = T::create(vrMain, config, itemNameSpace);
    if (typeid(ParentType) == typeid(VRDisplayNode))
    {
        VRDisplayNode* displayNode = static_cast<VRDisplayNode*>(item);
        displayNode->createChildren(vrMain, config, itemNameSpace);
    }
    return item;
}
```

Let me know what you think.
Ben

**Comment by BenKnorlein** [comment]
I added the possibility to start remotely when a "HostIP" is set. If started remotely also a "HostDisplay" should be set.
In addition i changed how the commandline arguments are read. Additional arguments can now be provided over the commandline with "Namespace=value". The value is then added to the DataIndex after the configfile was read which allows to overwrite Values with the commandline. This can also be used to allow additional parameter for the application itself as they can later be read from the DataIndex. I did not see any other way for this yet. (Note: It does not add them in the ssh-command yet). 

Ben

**Comment by BenKnorlein** [comment]
I added all commandline arguments to the calls now.

**Comment by BenKnorlein** [comment]
PS: Hope to test it this week in the YURT. Only the config-file is missing

**Comment by dtorban** [comment]
This pull request has been merged into the master.

**Pull request closed without merging**
