### PR TITLE
Issue117

### PR DESCRIPTION
**Pull request by dankeefe**
Addresses issue 117.  

- Resurrected MVRLookup by moving it to a new utils directory -- advise if you would like it somewhere else.  It doesn't seem like a test to me.  It's not flushed out as an example that we would want outside of the core repo.  So, I think of it as a util, but not sure if we envision ever having any more utils???

- Fixed a typo, "tests" -> "tests-batch" in CMakeLists.txt to make "make test" work again -- testing via command line building on OSX.

- memtest was crashing for me because it couldn't find its test.xml data file.  I updated cmakelists to install this file to install_prefix/share/memtest/test.xml.  Advise if you would recommend it be somewhere else.  Updated the memtest code to look for test.xml first in the cwd, then in an install pointed to by MINVR_ROOT or the install_prefix defined when the lib was built.

### CODE REVIEW

**Comment by tsgouros** [comment]
Sounds good. Memtest (and the other tests) will not be installed, so it doesn't really make sense to install the test.xml file in the install directory.

I don't know about other utilities. It seemed to me that MVRLookup might be useful for Python apps, but  not really sure. What's wrong with bin?

**Review by tsgouros — CHANGES_REQUESTED** [review]
Oh, ok. I thought it was installed into a new utils dir, not sourced in a new utils dir. I guess that's ok.

But I don't think test.xml has any business in the INSTALL_PREFIX directories.

**Comment by dankeefe** [comment]
MVRLookup:  Are we on the same page with this one now?  It looks to me like it was designed not as a test but as a utility.  But, it's also not big enough to be an external example.  And, it's not part of the libMinVR source.  So, it seemed to me we need a new place to source utilities, and utilities should get installed in bin.  My only question is whether we expect to develop any other utilities like this?  Or would this end up being a separate source directory with only one project in it?

Memtest:  A couple questions on this one:
- The interactive tests seem useful to install, kind of like glgears these could be "sanity check" test programs to run when you setup a new display or upgrade your graphics driver and suddenly everything breaks, etc.  But, I would agree that the other tests do not need to be installed.
- Can memtest be setup as another cmake test?  Right now I don't think it's part of the cmake testing framework, just a separate exe, right?  For things that are part of the testing framework, cmake let's you set a current working directory for the test, so this would be an easy way for it to find a data file from within the source tree.
- What didn't seem right to me in the orig memtest code was that it was looking for the data file using $MVRHOME/tests/config/test.xml   But, wouldn't MVRHOME (or MINVR_ROOT) be used to point to an installed version of MinVR not a source tree?
- Seems like the best solution here might be to convert it to a cmake style test?

**Comment by tsgouros** [comment]
We can lose memtest. You can run the cmake tests with memory checking via 'ctest --memcheck'. At this point, I don't think memtest adds anything significant.

MVRLookup was meant to be a generally useful utility. I misunderstood your earlier comment to say you meant to install it in a directory called utils.

**Review by tsgouros — APPROVED** [review]

**Comment by tsgouros** [comment]
And yes, the unit tests that are run with cmake's 'ctest' program (also 'make test') do not need to be installed. They can be run after a build to make sure everything works. They are simply unit tests I wrote to establish the data index operation and regression tests I added during debugging.

**Comment by dankeefe** [comment]
Ok, shall I remove memtest and installing the data file for it from this pull then?

**Comment by tsgouros** [comment]
Yes.

**Pull request merged**
