### PR TITLE
Implemented Threading Plugin

### PR DESCRIPTION
**Pull request by dtorban**
Hey Everyone,

I implemented a simple threading plugin which has a [VRThreadGroupNode](https://github.com/dtorban/MinVR2/blob/threads/plugins/Threading/src/VRThreadGroupNode.h).  This is a VRDisplayNode which enables all of the child nodes to each run in their own threads.  The synchronization points are at render(), waitForRenderComplete(), and displayFinishedRendering(). (i.e. glFlush(), glFinish(), SwapBuffers())

The cool thing is that the VRThreadGroupNode can be nested, so you could have several layers of threading.  In other words, synchronized display threads which also have multi threaded children.

I created an example config [multithreaded.xml](https://github.com/dtorban/MinVR2/blob/threads/examples/SimpleOpenGL/multithreaded.xml) inside of the SimpleOpenGL example.

Let me know what you think.  Here is a link to the plugin code: [Threading Plugin](https://github.com/dtorban/MinVR2/tree/threads/plugins/Threading/src)

Thanks,
Dan

### CODE REVIEW

**Comment by dankeefe** [comment]
That looks pretty cool Dan!  Can you see if it works for rendering in the Cave?  We might be able to finally do a performance test of multi-threaded vs. multi-process rendering.
D

-- 
Daniel Keefe
Associate Professor
Department of Computer Science & Engineering
University of Minnesota
http://www.cs.umn.edu/~keefe

On July 2, 2016 at 5:01:32 PM, dtorban (notifications@github.com) wrote:

Hey Everyone,

I implemented a simple threading plugin which has a VRThreadGroupNode. This is a VRDisplayNode which enables all of the child nodes to each run in their own threads. The synchronization points are at render(), waitForRenderComplete(), and displayFinishedRendering(). (i.e. glFlush(), glFinish(), SwapBuffers())

The cool thing is that the VRThreadGroupNode can be nested, so you could have several layers of threading. In other words, synchronized display threads which also have multi threaded children.

I created an example config multithreaded.xml inside of the SimpleOpenGL example.

Let me know what you think. Here is a link to the plugin code: Threading Plugin

Thanks,
Dan

You can view, comment on, or merge this pull request online at:

  https://github.com/ivlab/MinVR2/pull/44

Commit Summary

Implemented the threading plugin.
File Changes

A examples/SimpleOpenGL/multithreaded.xml (47)
M examples/SimpleOpenGL/vrexample.cpp (8)
M plugins/CMakeLists.txt (10)
A plugins/Threading/.gitignore (58)
A plugins/Threading/CMakeLists.txt (122)
A plugins/Threading/README.md (4)
A plugins/Threading/src/VRRenderThread.cpp (72)
A plugins/Threading/src/VRRenderThread.h (38)
A plugins/Threading/src/VRThread.h (106)
A plugins/Threading/src/VRThreadGroup.cpp (75)
A plugins/Threading/src/VRThreadGroup.h (86)
A plugins/Threading/src/VRThreadGroupNode.cpp (67)
A plugins/Threading/src/VRThreadGroupNode.h (46)
A plugins/Threading/src/VRThreadingPlugin.cpp (49)
A plugins/Threading/src/boost/BoostThread.h (61)
Patch Links:

https://github.com/ivlab/MinVR2/pull/44.patch
https://github.com/ivlab/MinVR2/pull/44.diff

**Comment by BenKnorlein** [comment]
Nice!
Just some questions: 
- Does it have a dependency to boost and if so, how do you link it with cmake? I did not see anything in cmakelists.txt
- I checked the VRThread.h and could not really find a Thread class. Maybe call it VRBarrier.h.
- Should we have a Thread class in MinVR core? I think it would be useful to have some things multithreaded, e.g. inputdevices. Having a platform independent base thread class would make things easier.

**Comment by dtorban** [comment]
It doesn't have a dependency on Boost, but you can configure it to use Boost instead of c++11 in CMakeLists by adding the definition -DUSE_BOOST.  Like you said, there is no option in the CMakeLists right now, but we can add it.  I can also get rid of the Boost option, but I figured perhaps for some environments it might be nice to use Boost instead of c++11.  I'm not sure if this is the case.

There is no custom thread class.  VRThread.h is a header with a bunch of typedefs for the already defined types.  i.e. typedef std::thread Thread;  typedef std::unique_lock<Mutex> UniqueMutexLock;  If you define USE_BOOST, these will be typedefed to the Boost types.

Having an abstract Thread class in the MinVR core is something to consider, but I imagine the implementation could be in the plugins to avoid adding any dependencies.  Would we also want to also have abstract Mutex and ConditionVariables for thread synchronization?

**Comment by tsgouros** [comment]
I think the Boost threading exists because it wasn't in c++ prior to 11. If
we are requiring c++11, then I vote to leave out the boost, but my code at
least doesn't require c++11.  Does anyone else's?

 -Tom

**Pull request merged**
